### ISSUE TITLE
Can not vote

### ISSUE THREAD

**Issue by anhntv2012** [tomochain/tomomaster#201]
<img width="960" alt="screenshot 2018-09-14 11 36 53" src="https://user-images.githubusercontent.com/42865525/45530020-a90e2a00-b812-11e8-9d39-c08ef3956c2e.png">

I voted for Masternode "Earth" 2 times, 10 TOMO each time. My balance was deducted but the "Total Voted" and "Candidates" remain blank.

**Comment by thanhson1085** [comment]
I saw you voted 2 times (30 TOMO, 10 TOMO), https://scan.testnet.tomochain.com/address/0x8f940e07a7e229a8224f88f349f6801ad68265a4

The votes was recorded in smart contract, but there is use with display the data it TomoMaster. We will fix it.

I have to convert your address from image to text so that i can test your case. So it is better for me if you paste your address in the description.

Thank you for the contribution

**Comment by thanhson1085** [comment]
I deployed a hotfix, it should for now, please check it again @anhntv2012

**Comment by anhntv2012** [comment]
It works perfectly now. Much appreciated.
