### ISSUE TITLE
Name, Total reward, Time left till being able to withdraw

### ISSUE THREAD

**Issue by anhntv2012** [tomochain/tomomaster#208]
a. It would be great if the following specs could be added:

1. Names of Candidates/Masternodes should be added everywhere. It will be much user friendlier.

2. Summary of Rewards gained by voting for each Masternode/for all masternodes.

b. Incorrect estimated time left till able to withdraw. 
It should have been 48 hours, not just about 5 hours after my unvoting
<img width="960" alt="screenshot 2018-09-15 15 08 23" src="https://user-images.githubusercontent.com/42865525/45584315-7be97680-b8fb-11e8-8b8f-54485f3e28b9.png">

**Comment by thanhson1085** [comment]
a. -> good suggestion

b. you are right, I already known the issue, but it may not be fixed in testnet. But in mainnet, i sure that is 48 hours.
In current testnet, the voter's locked time was setup 4.8 hour (instead of 48hour), and was recorded in genesis block (the first block of blockchain), so it can not be changed, unless we reset the current testnet.
