### ISSUE TITLE
Sorting is inconsistent

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomomaster#263]
Sorted by age, 6 days is before 13 hours.
![image](https://user-images.githubusercontent.com/26155267/47693351-f7914f80-dc2b-11e8-9890-b17430998abd.png)

**Comment by pqv199x** [comment]
Since there is no good option to sort 'moment fromNow' datetime (a day ago, 2 minutes ago...). I suggest that I will remove sortable from Age column and update sort query db, so latest tx will display like other tables (Masternode Rewards table, voter reward table...)
Like this:
![image](https://user-images.githubusercontent.com/24842503/47841611-ca3fcf80-ddec-11e8-9d7c-08cbc709c772.png)
Are you ok with this? @etienne-napoleone @thanhson1085

**Comment by thanhson1085** [comment]
ok

**Comment by pqv199x** [comment]
Fixing pull request:
https://github.com/tomochain/tomomaster/pull/280
